spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.234.128:3306/gulimall_ums
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.234.128
    port: 6379
  session:
    store-type: redis
  application:
    name: gulimall-member
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8002
#seata:
#  tx-service-group: seata-storage-service
#  service:
#    vgroup-mapping:
#      seata-storage-service: default