spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.234.128:3306/gulimall_pms
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
      name: gulimall-product
  data:
    rest:
      return-body-on-create:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
  redis:
    host: 192.168.234.128
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 360000
      use-key-prefix: true
      cache-null-values: true
  session:
    store-type: redis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
server:
  port: 8003
  error:
    include-binding-errors: always
  servlet:
    session:
      cookie:
        domain: gulimall.com #放大session作用域
        name: GULISESSION #更改session的名字
      timeout: 30m
logging:
  level:
   com.yang.gulimall: debug
feign:
  httpclient:
    connection-timeout: 5000
    ok-http:
      read-timeout: 5000
# ribbon.ReadTimeout=5000 ribbon.ConnectTime=5000
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

