spring:
  application:
    name:
      gulimall-seckill
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  redis:
    host: 192.168.234.128

  task:
    execution:
      pool:
        core-size: 5
        max-size: 50
  session:
    store-type: redis
  rabbitmq:
    virtual-host: /
    host: 192.168.234.128
    username: itcast
    password: 123
server:
  port: 8010
management:
  endpoints:
    jmx:
      exposure:
        include: '*'
