spring:
  session:
    store-type: redis
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search
  elasticsearch:
    uris: "192.168.234.128:9200"
    socket-timeout: "10s"
#    username: "user"
#    password: "secret"
    restclient:
      sniffer:
        interval: "10m"
        delay-after-failure: "30s"
  thymeleaf:
    cache: false
  redis:
    port: 6379
    host: 192.168.234.128
server:
  port: 8006
  servlet:
    session:
      cookie:
        domain: gulimall.com #放大session作用域
        name: GULISESSION #更改session的名字
      timeout: 30m