server:
  port: 8009
  servlet:
    session:
      cookie:
        domain: gulimall.com #放大session作用域
        name: GULISESSION #更改session的名字
      timeout: 30m
spring:
  application:
    name: gulimall-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.234.128
    port: 6379
  thymeleaf:
    cache: false
gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
#seata:
#  tx-service-group: seata-storage-service
#  service:
#    vgroup-mapping:
#      seata-storage-service: default
