
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.234.128:3306/gulimall_wms
  rabbitmq:
    username: itcast
    password: 123
    host: 192.168.234.128
    port: 5672
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual #手动ack
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: gulimall-ware
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8004
logging:
  level:
   com.yang: debug
#seata:
#  tx-service-group: seata-storage-service
#  service:
#    vgroup-mapping:
#      seata-storage-service: default
